apiVersion: v2
name: wallet
description: Chart holder for ArgoCD
type: application
version: 1.0.78
dependencies:
  - name: dome-wallet
    condition: dome-wallet.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.4.22