---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secret
  namespace: tenant-blue-identity
spec:
  encryptedData:
    admin-password: AgAlqULNrO801MBnLZoNZUCr57QaaU4lRZabRbJg8kfOHCRFtl93l6txrkyxuVPBu4MXcHAq5chSlH/2SeNPthWNwN7X8MnY51j8TCPLZzzhRydEuSb2LD5aXHibIWwfCUMTtBdRC+B4Cj/PkIoh44SXVdPZU/kGtNjpHrW+XYoV7j0Xxi4nnvCxlp5r6XT7F6qKKa6lX5yrfgTsPht0DmQ7V0I8kvuUYSpH/Nw6ubzrMUR0nlIRy4LrPYoZ6zD9u5Dz9NYMJ5YA7aiSZpiS8FZd0ST1KOg5cN0R/xIdolJCrKtyyraQdIYXU+xbvlQVkuCiI9GpZnF+oMczgLVeE8RG1Dl+DPaPbO2tZNIqYWrM1OBxBna7CBFZcP5Y6dBpbcWwCNFn9FE5S4TJ3hTAXHpDxlfkh9VkfDpnAqppvr65yeTTim+sAVJNNym9h1H09PNSlZOZfTxj0Dkivlpx6unoo7TgrKwa0ie+2xIS8RDizoKSdQ18a2HbmWWMmSyBjNNbTzfuBhfMihUdlaqi4NLN42NwD/jyQbCAfLfm0bD6XaszexT7ASkakSh1KzX88sVoXQoIUgHO985X2JCYLOp23WS7HQieYhKLQKomp84G/7+0yx405UDIh+atKIm4UuvjH1fWeYPHoNq3/MYH0oQNZLoJEfMDOzNjbGXSQnUdINuKpEmEVVAmcSsslPqT9U1XBUp1Bw==
    db-password: AgCmCNB6fLe6zU3Dizkc+enlfiFLKG+a1uSFKGjYh9Zlz3yhs+AWFuZwP4ld/y+VURNbijNdv7FR7FsYwcqKiIRaDcgcKVNk6uty7NPT6+gAVXlR3xC8XALEbZwM2fmTjBswzCI/1Hfa+EY71Zgi1vnyv21r1vtGCXxWYDNS/4Df+uvNBt30hkk214ozXHiioC4iba4+5iNfkw9Xu5+w4eBvmAjhz6Zx3VdIkDrkkzMbDpOynMt4/lcsPczBRMSAzVUOvn2BA7iKcnO9bu1dh6+CbsfK/wMG9PM/qIXYlCMNSg1mblyUG/SS1ckaYXbjgxakCZUSwzBIRTG1EPF538uYBBmGYomYGzJV+jtT836c9nMav3anHv9MR3ihEspVvbza62GA+6OrKOKzQwL7zZZzLfg4AMHB9OdHT31akj7hJt3mkCKqMJfbxjBnHzbwcGRe38aKs9GBVxyMHYEDvtI2iURaBEBwjqqC6wn9DYMZNok3E4bN+L6G69Gg09uafH5IHP0HnOoVAyTT4jEIhURhTlTiVCXkwwXvN/cFAyD9rtDdZHrvolCu9WoyqX22VoZ6BTTONcA3YfSR6NxOQZJY+llhsfwNcPU+P8yl50P7G6YtucTBU3PwQ+DaoJi/wCME+ijcbnTOWX/lSbxjN1gUVys+NgP5O1ULRFXc93Bcav8KR4qvU7BCgoJccQUZnd6FWwij+q50LQ==
  template:
    metadata:
      name: keycloak-secret
      namespace: tenant-blue-identity
