---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-env-secret
  namespace: tenant-red-marketplace
spec:
  encryptedData:
    MONGO_BAE_BELP_PW: AgB9LQgfBz97zVcXFetz46g/Z9nY1dzumHnraI1xjvad6rWwWWlt2K4tI6/1yutugme1MFb2l+UdsVMVpJUKfGT1iqM1durUdiwNk1H86cjHsX2lSJqExVs5feRSAU09E6qxSkq5Z/iap9UuXg4GQ0jQpnQbz59tJ3P1lbFTxwh3RkGZcyqQ4Ny52NUy/TzKmEgNXYe/3SwYxxdjYhn4JN+IK6aVf8dE+D0k9HLzERtje1lQbHaHiiwQpoq8qwYTV0DkQKdM8qqPvIJjdhJ1aQmaGvajuAv4BHSEreXUWzQuUs+ZFpzZ2amIXxe5CmMw4hK/lsPqakSFVdXi+eDt+XTrWrW0xc2FoqiymF5ZOmFwt50UiPpwG3KvoHQdfwgpt+nWwccXcXhk5ZVUVm2cPJ95OEhORBRaedezXniMDtDQHZTU/iWw1VJW2Fn3iVlmLm5PNRFR3kcVCPslOUF/sGiiv0cM4PBRsv5MA9t9BB0CPGTLXNC2WBQzoQNgdWajo9Np1h/hhBwyHzJhVaEB5v5iXysNevCQu2AU32aDXIeSUoR60MbBbO06jEsbYzjkPHPmzZTw+GKIuolpt2txhYEyXZ1OD4jlIZdWaAAW6Fsnbk5Z+J+L7IArSJMJfX/nNWWmWL1yHZyphP9Q4uecZEwGTpJLCvgpFSqIJ1kCJGXJI1upGA1PPW30BiN31lObA/x6WTJco3wxRD5Vs7g=
    MONGO_BAE_CHARGING_PW: AgCO6GpMlI7Cci5FtnIjpJBYJKY1vwiFM24jaiVGvKB2qZX1Jz/2ancPUxfJK+KqjmJaP+COpoxmsfGAt6Uv/yS6OX5L1giaDGk0Z9w28FcBoJnMXTx9DUODfBh0bGu7YvoSu2KYmi51MUCksjb+fEczwY4dOBlWvo5nHbNEdpr4mx0fWw5WGtFNgfE2YHUwEGczwmNppDme9zR7VJaA4NpoOJ21HiOf5KqVlphSw5UHlvUin3XTEFvPFXM+WHtbOF2xJNSq/sdjl1cPp4LHU1HWvucPCTnX3cN6eFDJVkjlksHbAEYvkWY/sMDAatpklHK7CuzyNaqUEOq2lYiziimdDQLgYDCHldbJSjchCwVhqPD0do2ne5UJGD/bUAL+LwwINYlNFYOIcVRPINVvgd4Z+qnPkOmcP6FRb7eVdXDtT7QcEy3NfPzvW/byAtMcnhQlOoqoUYFfBqG3MjUrlGHBHdRaI80yuCrHmNotbIeVFrP8dKjsHNWYtzrei3kFFRAIOuNnSQiEkSFTcYuHWI0mP4cikLhEp6L5Cm6rR37C4on/Jo5Gmz3fgj9a3aqHTjZdb0k67LFm1X3eh+HfwhPm09QjRHFBpAbS5WE9zUQzAy7epG33Ez1nI9iez6EghULzetuMWN4aztQtKgfI5l9vZQkKXLrNOChG1naksLEayf71nq3meeNhMnW3aZDh5TJeBkU7iZ47NIjdixE=
  template:
    metadata:
      name: mongodb-env-secret
      namespace: tenant-red-marketplace
