---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: tenant-red-marketplace
spec:
  encryptedData:
    mongodb-root-password: AgBtuBk/sfIdeP0XvOFPvG9VJNZQKAA5KjVTaagvOkeCUhP0+g986kolylD7zOLbY9B5dzHXxuyhH0whLsQcbGFdTw7dH3LyZ6ksB9+vYyZSqcb1X1DG/vbfckNoMw4/CBeyneYdmShzzh8gCA+BtRJU4Jm1kfRbFr3OcSIZkHpyTZ2tTMG4PaEzdfh5yxH08ZSvxlr5hT9VkWmKDN0EaEbTCdWyiko7m8YMpnZt9fuQwTKFFGpn8C1InLswAw9LcJPQON5ydBWKZSvOJlv2/tHddvuZNHsXTd7OvxYhhoHMXHlx8R+V/I94+limbRaywO6giCHyIE2eF0Op5YhfaoDOQyY2ZWlaEkOtnTrQ7WXyTAfaD4K/Ul6vuHpwWTcWOzSbCf/DTvjjkhJZYhPkDcbOe5jkNWfjNamSCs0HrgV7RDjm7+x3dpx/jNi0aVEXi54tVRO030djpaGCLdFYm1mjcoVZqB0eogx2T/dPxJIHwDm09UeOWiVfa5fVstbtcz5DEpN9tK8u1YCxaJ3Hc4MbyFMjbDmzZ5xNcavag2/iP7mhNi99vfJ4ddiCRWxiNAmPnx2UG+Av4X/QMwqhtJuC+iHpd5T25eDkON6rK+r0a8JTLEv3xrFid4x2fnrT62MCXun0651PWE0cydp7QJhb11hwrQLLhGlvcxJ2rVyF4pH9z3KE/4cEPMi96Lncsl9uoaL7zEMuZ58ZNGY=
  template:
    metadata:
      name: mongodb-secret
      namespace: tenant-red-marketplace
