apiVersion: v2
name: trusted-issuers-list
description: Chart holder for til

type: application
version: 0.3.12
appVersion: "0.2.0"

dependencies:
  - name: trusted-issuers-list
    version: 0.3.5
    repository: https://fiware.github.io/helm-charts