---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-refresh-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-refresh-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-refresh-rolebinding
subjects:
- kind: ServiceAccount
  name: ecr-secret-refresh-sa
roleRef:
  kind: Role
  name: ecr-secret-refresh-role
  apiGroup: rbac.authorization.k8s.io
