apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-check-rolebinding
  namespace: tenant-red-identity
subjects:
  - kind: ServiceAccount
    name: vault-check-sa
    namespace: tenant-red-identity
roleRef:
  kind: Role
  name: vault-check-role
  apiGroup: rbac.authorization.k8s.io