---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secret
  namespace: tenant-green-identity
spec:
  encryptedData:
    admin-password: AgA+7Sz+4QSE+OuIMtKriLNaPcSKIflAwVx2rat8y87CTZLZjAkLe6TvoSuTzyJhtx/q3FM1qF4oNhJhgoNHbmWxBBpFZdQqzq23BGZzxk09YN/XwUL57+wZH7FR4Zy6F6VY4kwr1qkKr7UiOiLzjilnIDDJ2ZyOKRlrONfxlw63Rdqp+LYSHQg+UZhzto6hpoBguPYKrnmQsb15/wd/SJ4bBf5D4fSm5ko3bmnsbphxY/eiC8jcFEfrbyJe+EGh44M0MIyzUuuuv8QcJzkN2UMO9OskzoF/AdcFUp81nj+5zS2WwDPaX7NxTQSto/+uyZUwpeckWmbX/TLLe9DzpPdCMAWBb0Ytn4oArCn5lq4kpdY2/6OMchBr3o1kdrae+FmO2FkdgdoMm7pkFGhau4hsw/e7usNB/l72Q5rUPIxgM8+cygMsryMDXIA5I4zE/skYj7KJl/AF9C4nCdqGj2kD8DvNJcNKqZkjDTzBWIjTY6RKxlnPiOOxxQ0pEJP0HkOX+/dXJa5DOuQIsYgbEV0qGRNyNrzmUregWZby5/7OoZM5bjlDIGkuGTMuWqXESkEohef8/YMB1PR3oTc8+0WMpUF5r4XmVb8H0plb5SGggr98QiWBFPjFiwhNXQFbNOTAqwrqawvwWnxhcMwbo75NnBbo6OfMDWVLF249Au1sXqZCaygW3+Dgt+06nx8DqqVqip0VcA==
    db-password: AgBL3x5tClAohyU5OPecQqdUVtHC7JT8YX9yIZhycVEutGGl+Mxx88WAdewIn/wqFaiYF+1jWMb+SP3ZBfupVGd6238roGgocCkEsmSA4FlYtf06Ignapdj6AhFWWeXDmn5zbG/yqDvuIJcIYeO0IctO5XfWJ/2aVTnNc8kgi1octI1edZbmVp/YhzccR3I9ZwRu0OVe1QHU3TC8wze91A6E7sWpC2GSoCwdj6rFNcsNB2HAWi2WzaXoCehWGL9qhHmwABgRKtFv2Wix9ae+0U9ByatvbMWw2hwi2lYKPq1kOMwAwVYgSpk0rYflxMN5nQ2M5BklQhDcVTxlWWOPKiJSKiRzZErCA2zYHciCZErAzl5mah28mHZQ5+HTzk+LU/eDYbrBrab10qKLjMljeqTW2uEvuMM5YHh0DiGk9GFA/fh2+6Uw5OryLY1+g4oLvG7O7LgQPRieoIEmTmczvy57PIPpboVOEBuyzmh5IgulRH5ijz88YHfMGUNJkyZxPVK3c5PxK88coG0HdTtpvD3nph8+cmgilI2PcQGChwFz2/fp8C3btSWHu7lkAxaRBMXRv/M+5S1ziK+8+7ASp8jcmRlt/bkSzuM0b3yrk0AdJZEzbQoyuGnXokIwjnf04aecq6+XnyL8xdwZBqjvgBzNy0zkNuLx8PmvULESjKaKd3bvXOGIEL6GN2vh+L0QN+QoLpQmMX7Drg==
  template:
    metadata:
      name: keycloak-secret
      namespace: tenant-green-identity
