apiVersion: v2
name: tenant-blue-identity-issuer
description: Chart holder for ArgoCD
type: application
version: 1.10.225
appVersion: "v1.0.11"
dependencies:
  - name: eudistack-issuer
    condition: eudistack-issuer.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.0.19
