---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secret
  namespace: tenant-red-identity
spec:
  encryptedData:
    admin-password: AgCakjmzoGcE20GQ1xWyVcsCeQE2Aq1JX/ifLvFKa1gwdo+ZBa2upHmgcYXVy+9pn3lxTbUuBP6ISq8sn8vxrvLRCeBCrKk8eDN3nL7Rkue0U1h/lnX8C9qno8XTfXQQcc3qFBJ6FnbQjCPcdLcSKHUUttSnaMIFr60I2rOHGlDXx4jmgP9wKYpRpB5b3yCUzzx3qKT/gbZGkns8KqjbDZfJRYLx+gxMZC4QNGXk9yImcbd4pTknAfC332gT5zv3NUGpe/ofV+IEA/fa0zPdihcHBmy7eX+/J5bT0xv8sGUEDII69BshbjBUaTq4WhMtdsJyOBOtwcxyctLHrkOlwWkxeJUCniiZvgeiEPIgx96QdHMkqlm+wnveVWpBT/NAIPbb8QPzsU9k0oYGgFr9fiiXKNlbASG+yRia+gB7gtgwTBOV/UYyNjwite70b5ppr2uQ1zDwFWnUOnI+7m5voaIs6evloMyLKMVmesq8BYx3Q07p1vNvBHgf4+0l4b9vx8dKWJR6Q8hvNflOp7oxIsQ+qCvM7xMw9FwjMzmaFE2bJqiaMSwXytY+FCiiqrtrxZoXLr1BZy+3wnpkbTRV0FkTs72tFlTP7g/5YrQZj4HxrP7F3NL5icQ04/sstHdm6o+6BcjH4irEqMuRveLhY2ffebcpdbfabbsa1LINMlFmmm+UlORT364fgIgWom8MGPIm5uTShQ==
    db-password: AgB48kF1F3rRvifMZysiZK2+YlwaBosReyqKK0eXuHWkUs5sdovdptNnzvOmU5VGZx2kr4q+zZ1/RIzeTq4OL/b59kGh1/lF18kNaKts5Nrg6XKwmZb8hhRevWfUbiuvlxdK+iv6WFtvepDkyg1SzuMfEqAn2MNiIapA6a5hNXrTgTbvnrIT+8ub29MSidsPb83XaEQMGG1nvpWdGj4YGxPHRLyQijGrzJI5CJvG6z6Z56BBaeSBy+MxnHMLH5u1cWSIS+NyHhb24RL/aJEGbQugkni+z7D4RNRnccgEg3COeeDxQUFp3Qsrbns0nbfLzT4bDcOAGUnmZjMBLphYuTcxigWjFFLwhiCGA6kxU30pKPLpEVzcGVYoP5DI59qM3IQ8d2dSPOB+EsP+nYglPJTFiTbEzPHpjhVdINNPJ6S8jHazCXYR5N8PKwmKAvxY+9AFK+nbgtSMNMpvJg17EcPOK3W61NcWUluj7TTpyx2xshOTVEN0jiAosL2u9pYWwxZPM+0gijKL9wgc4OeARTw6pHbiOzuEoDOOJR8RFuT8WbGZJO0S3WpyUpK0VDvkkg6yM0pL+4Q9rF63HIRvgAUGe/cvm4SdDFEod98+gQqcRreB1c0jDKgh9rKsPV9M8AKnt9gaB654m9NVuNaSvQx+cgkFZP194vZYYMO/IY2tt88qg7QeX8Zn+WzxyBfp5AfPRqSypcyKhA==
  template:
    metadata:
      name: keycloak-secret
      namespace: tenant-red-identity
