{{- if and .Values.adminer.enabled .Values.adminer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "database.fullname" . }}-adminer
  labels:
    app: {{ include "database.name" . }}-adminer
spec:
  rules:
    - host: {{ .Values.adminer.ingress.host }}
      http:
        paths:
          - path: {{ .Values.adminer.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "database.fullname" . }}-adminer
                port:
                  number: {{ .Values.adminer.service.port }}
{{- end }}
